### ISSUE TITLE
os.getlogin() throws [Errno 6]

### ISSUE THREAD

**Issue by dblossom-marist** [dblossom-marist/PerfMon#20]
os.getlogin() is throwing an error in Ubuntu 18.10. Seems to work fine when running manually but **systemd service python.service** is not starting. The following is observed within **journalctl**:

```Apr 20 14:31:50 perfmon-pc python3[23699]: 2019-04-20 14:31:49.055040
Apr 20 14:31:50 perfmon-pc python3[23699]: Logical CPUS: 1
Apr 20 14:31:50 perfmon-pc python3[23699]: Physical CPUS: 1
Apr 20 14:31:50 perfmon-pc python3[23699]: Traceback (most recent call last):
Apr 20 14:31:50 perfmon-pc python3[23699]:   File "/usr/share/perfmon/MetricsCollector.py", line 30, in <module>
Apr 20 14:31:50 perfmon-pc python3[23699]:     go.run()
Apr 20 14:31:50 perfmon-pc python3[23699]:   File "/usr/share/perfmon/MetricsCollector.py", line 24, in run
Apr 20 14:31:50 perfmon-pc python3[23699]:     proc.updateDatabase()
Apr 20 14:31:50 perfmon-pc python3[23699]:   File "/usr/share/perfmon/Processes.py", line 71, in updateDatabase
Apr 20 14:31:50 perfmon-pc python3[23699]:     # TODO: Do we want to get more granular?
Apr 20 14:31:50 perfmon-pc python3[23699]:   File "/usr/share/perfmon/Processes.py", line 39, in collectProcesses
Apr 20 14:31:50 perfmon-pc python3[23699]:     #uname = os.getlogin()
Apr 20 14:31:50 perfmon-pc python3[23699]: OSError: [Errno 6] No such device or address
```

**Comment by dblossom-marist** [comment]
Testing a local fix using `getpass.getlogin()` from `getpass`.

**Comment by dblossom-marist** [comment]
`getpass.getlogin()` doesn't seem to work properly in backend situation due to the nature of having to run root. Continuing to investigate ... leaving bug open but making it a low priority assuming GUI is working with flag as intended. The backend scripts **want** and **need** to collect all running processes for database anyway.

**Comment by jmuf** [comment]
`os.getlogin()` need a TTY, which will not be the case for things started by systemd. Suggest to use `os.getenv('LOGNAME')`  (or "USER").

**Comment by dblossom** [comment]
Thanks. We tried that but ran into admin issues or something. Anyway, this is a stale project we did for a school assignment. But your suggestion is appreciated.
